version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cert:/etc/nginx/cert
    ports:
      - "443:443"
    links:
      - app
