#!/bin/bash

# GO UNIT TESTING (includes static checking with go vet)
# ------------------------------------------------------
echo "GO UNIT TESTING"
echo "---------------"
make go_test
if [[ $? != 0 ]]; then
  echo "TESTING FAILED"
  exit 1
fi

# JS UNIT TESTING
# ---------------
echo "JS UNIT TESTING"
echo "---------------"
make js_test
if [[ $? != 0 ]]; then
  echo "TESTING FAILED"
  exit 1
fi

# GO FORMATTING
# -------------
echo "GO FORMATTING"
echo "-------------"
make go_fmt
if [[ -n $unformatted ]]; then
  echo "FORMATTING FAILED"
  exit 1
fi

# JS FORMATTING
# -------------
echo "JS FORMATTING"
echo "-------------"
make js_fmt
if [[ $? != 0 ]]; then
  echo "FORMATTING FAILED"
  exit 1
fi

echo "COMMIT SUCCEEDED"
exit 0
