# This is a basic workflow to help you get started with Actions
name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Karma
      run: npm install karma karma-jasmine karma-chrome-launcher karma-firefox-launcher karma-coverage karma-spec-reporter jasmine-core --save-dev
    
    - name: Test
      run: ./node_modules/karma/bin/karma start tests/karma.conf.js --browsers FirefoxHeadless --single-run

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
